{% set name = "public_suffix" %}
{% set version = "6.0.2" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: bfa7cd5108066f8c9602e0d6d4114999a5df5839a63149d3e8b0f9c1d3558394

build:
  noarch: generic
  number: 0
  script:
    - gem install --norc -l -V --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem

requirements:
  host:
    - ruby
  run:
    - {{ pin_compatible('ruby', max_pin='x.x') }}

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/public_suffix
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: PublicSuffix can parse and decompose a domain name into top level domain, domain and subdomains
  doc_url: https://rubydoc.info/gems/public_suffix
  dev_url: https://github.com/weppos/publicsuffix

extra:
  recipe-maintainers:
    - jdmarques
    - sodre
    - svengiegerich
    - janjagusch
