{% set name = "public_suffix" %}
{% set version = "5.0.1" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 65603917ff4ecb32f499f42c14951aeed2380054fa7fc51758fc0a8d455fe043

build:
  noarch: generic
  number: 0
  script:
    - gem install --norc -l -V --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby 2.6
  run:
    - ruby 2.6

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE.txt
  summary: PublicSuffix can parse and decompose a domain name into top level domain, domain and subdomains

  doc_url: http://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/weppos/publicsuffix

extra:
  recipe-maintainers:
    - sodre
