{% set name = "public_suffix" %}
{% set version = "5.0.4" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 35cd648e0d21d06b8dce9331d19619538d1d898ba6d56a6f2258409d2526d1ae

build:
  noarch: generic
  number: 0
  script:
    - gem install --norc -l -V --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby >=2.7,<3
  run:
    - ruby >=2.7,<3

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE.txt
  summary: PublicSuffix can parse and decompose a domain name into top level domain, domain and subdomains

  doc_url: http://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/weppos/publicsuffix

extra:
  recipe-maintainers:
    - sodre
    - svengiegerich
    - janjagusch
