schema_version: 1

context:
  name: public_suffix
  version: 6.0.2

package:
  name: rb-${{ name|lower }}
  version: ${{ version }}

source:
  url: https://rubygems.org/downloads/${{ name }}-${{ version }}.gem
  sha256: bfa7cd5108066f8c9602e0d6d4114999a5df5839a63149d3e8b0f9c1d3558394

build:
  number: 1
  noarch: generic
  script:
    - gem install --norc -l -V --ignore-dependencies ${{ name }}-${{ version }}.gem
    - gem unpack ${{ name }}-${{ version }}.gem

requirements:
  host:
    - ruby
  run:
    - ${{ pin_compatible('ruby', upper_bound='x.x') }}

tests:
  - script:
      - ruby -r ${{ name }} -e 'exit 0'

about:
  license: MIT
  license_file: LICENSE.txt
  summary: PublicSuffix can parse and decompose a domain name into top level domain, domain and subdomains
  homepage: https://rubygems.org/gems/public_suffix
  repository: https://github.com/weppos/publicsuffix
  documentation: https://rubydoc.info/gems/public_suffix

extra:
  recipe-maintainers:
    - jdmarques
    - sodre
    - svengiegerich
    - janjagusch
